config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'

  resources :posts do
    resources :comments, only: :create
  end

  resources :users, only: :show
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user


end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true
	validates :body, presence: true
	belongs_to :user
	has_many :comments


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

	def render_not_found(status=:not_found)
		render text: "#{status.to_s.titleize} :(", status: status
	end

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [ :first_name, :last_name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!, only: [:create]

	def create
		@post = Post.find_by_id(params[:post_id])
		return render_not_found if @post.blank?

		@post.comments.create(comment_params.merge(user: current_user))
		redirect_to :back 
	end

	private

	def comment_params
		params.require(:comment).permit(:body)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :show]

	def index
		@posts = Post.includes(:comments).order("comments.created_at DESC")
	end

	def new
		@post = Post.new
	end

	def create
		@post = current_user.posts.create(post_params)
		if @post.valid?
			redirect_to root_path
		else
			render :new, status: :unprocessable_entity
		end
	end

	def show
		@post = Post.find_by_id(params[:id])
		@comment = Comment.new
	end

	private

	def post_params
		params.require(:post).permit(:title, :body)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
      @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>MessageBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'https://js.stripe.com/v2/' %>

  <%= csrf_meta_tags %>
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Ben Kinney Message Board</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
        	<%= link_to 'Home', root_path %>
        </li>
        <% if user_signed_in? %>
        	<li><%= link_to 'My Profile', user_path(current_user) %></li>
        <% end %>
      	<li>
				  <%= link_to new_post_path do %>
				    <i class="glyphicon glyphicon-plus-sign"></i>
				    New Post
				  <% end %>
			  </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
	      <% if user_signed_in? %>
	        <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
	      <% else %>
	        <li><%= link_to "Log in", new_user_session_path %></li>
      		<li><%= link_to 'Sign up', new_user_registration_path %></li>
      	<% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if notice.present? %>
	<p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
	<p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html lang='en'>
<br/>
<br/>
<h1 style="text-align: center">Posts</h1>


<% @posts.each do |post| %>
	<div class= "booyah-box col-xs-10 col-xs-offset-1" style="margin-top: 0px; margin-bottom: 0px">
		<h2><%= link_to post.title, post_path(post) %></h2><br/>
			<i>Author: <%= post.user.first_name %> <%= post.user.last_name %> &nbsp;&nbsp; Started: <%= local_time(post.created_at) %> &nbsp;&nbsp; Last update: <%= local_time(post.comments.first.created_at) %></i>
	</div>
<% end %>

</html>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html lang='en'>
<br/>
<br/>
<div class= "booyah-box col-xs-10 col-xs-offset-1">
	<h1>Enter Your Post Details</h1>
		<%= simple_form_for @post do |f| %>
			<%= f.input :title %>
			<%= f.input :body %>
			<br/>
			<%= f.submit 'Create', class: 'btn btn-primary' %>
			<br/>
		<% end %>
</div>

</html>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html lang='en'>
<br/>
<br/>
<div class= "booyah-box col-xs-10 col-xs-offset-1">
<!-- Button trigger modal -->
<button class="btn btn-primary btn-md pull-right" data-toggle="modal" data-target="#myModal">
  Add a Comment
</button>
<h1><%= @post.title %></h1>
  <i>Started: <%= local_time(@post.created_at) %></i>
  <br/>
	<% if @post.user.present? %>
		<i>Author: <%= @post.user.first_name %> <%= @post.user.last_name %></i>
	<% end %>
	<br/><br/>
	<p><%= @post.body %></p>
  <hr style="border-color:#888e99" />
	<% @post.comments.each do |comment| %>
    <div class= "booyah-box col-xs-12" style="margin-top: 0px; margin-bottom: 0px; background-color: #eaeff7">
  		<p><%= comment.body %></p>
      <hr style="border-color:#888e99; margin-bottom: 2px;" />
  		<i>Author: <%= comment.user.first_name %> <%= comment.user.last_name %> on <%= local_time(comment.created_at) %></i>
    </div>
	<% end %>
</div>
<div class="clear"></div>
<!-- Button trigger modal -->
<button class="btn btn-primary btn-md col-xs-offset-1" data-toggle="modal" data-target="#myModal">
  Add a Comment
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add a Comment</h4>
      </div>
      <%= simple_form_for @comment, url: post_comments_path(@post) do |f| %>
        <div class="modal-body">
					<%= f.input :body %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit "Add Comment", class: 'btn btn-primary' %>
      </div>
				<% end %>
    </div>
  </div>
</div>

</html>

app/views/users/show.html.erb
<br/>
<br/>
<h1 style="text-align: center">My Profile</h1>


<div class="booyah-box col-xs-10 col-xs-offset-1">
	<h1>Name: <%= @user.first_name %> <%= @user.last_name %></h1>
  <h2>Email address: <%= @user.email %></h2>
  <h3>Member Since: <%= @user.created_at.strftime("%B %d, %Y") %></h3>
  <h4><%= @user.posts.count %> total posts</h4>
  <h4><%= @user.comments.count %> total comments</h4>
</div>